import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

function date(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString("ar-SA") : "—"; }
export default function AdminStudents() {
  const list = trpc.admin.students.list.useQuery();
  return <main dir="rtl" className="min-h-screen bg-[#f7f6f2] px-5 py-10 text-[#13233a] lg:px-16"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="text-sm font-bold text-[#0e7c78]">لوحة الإدارة</Link><h1 className="mt-4 text-3xl font-bold">حسابات الطلاب</h1><p className="mt-2 text-sm text-[#13233a]/55">الحسابات ذات الدور canonical: <b>student</b>، مع بيانات الملف والتقدم الفعلي.</p></div><span className="rounded-full bg-[#e9f5ef] px-4 py-2 text-sm font-bold text-[#0e7c78]">{list.data?.length ?? 0} طالب</span></div><div className="mt-8 overflow-x-auto rounded-3xl bg-white p-4 shadow-sm"><table className="w-full min-w-[1050px] text-right text-sm"><thead><tr className="border-b border-[#13233a]/10 text-[#13233a]/55"><th className="p-3">الاسم</th><th className="p-3">البريد الإلكتروني</th><th className="p-3">المرحلة الدراسية</th><th className="p-3">الصف</th><th className="p-3">تاريخ التسجيل</th><th className="p-3">حالة الحساب</th><th className="p-3">الملف الأساسي</th><th className="p-3">Smart Onboarding</th></tr></thead><tbody>{list.data?.map(({ user, profile, learning }) => { const profileComplete = Boolean(profile?.fullName && profile?.educationStage && profile?.grade); const onboardingComplete = Boolean(learning?.subject && learning?.stage && learning?.grade); return <tr key={user.id} className="border-b border-[#13233a]/8"><td className="p-3 font-bold">{profile?.fullName || user.name || "غير مكتمل"}</td><td className="p-3">{user.email || "—"}</td><td className="p-3">{profile?.educationStage || learning?.stage || "—"}</td><td className="p-3">{profile?.grade || learning?.grade || "—"}</td><td className="p-3">{date(user.createdAt)}</td><td className="p-3"><span className={user.accountStatus === "active" ? "rounded-full bg-[#e9f5ef] px-3 py-1 text-xs font-bold text-[#0e7c78]" : "rounded-full bg-[#fff3df] px-3 py-1 text-xs font-bold text-[#8a5b27]"}>{user.accountStatus}</span></td><td className="p-3">{profileComplete ? "مكتمل" : "غير مكتمل"}</td><td className="p-3">{onboardingComplete ? "مكتمل" : "قيد الاستكمال"}</td></tr>; })}</tbody></table>{!list.isLoading && !list.data?.length && <p className="p-10 text-center text-sm text-[#13233a]/50">لا توجد حسابات طلاب بالدور student.</p>}</div></div></main>;
}

