import { Link } from "wouter";
import { Heart, Trash2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { buildFavoritesCsv, buildFavoritesExcel, downloadTextFile } from "@/lib/favoritesExport";
import { useState } from "react";

export default function Favorites() {
  const favorites = trpc.student.favorites.list.useQuery();
  const utils = trpc.useUtils();
  const remove = trpc.student.favorites.remove.useMutation({ onSuccess: () => utils.student.favorites.list.invalidate() });
  const [exporting, setExporting] = useState(false);
  const [exportMessage, setExportMessage] = useState("");
  const items = favorites.data ?? [];
  const exportFavorites = (format: "csv" | "excel") => { setExporting(true); setExportMessage(""); try { const content = format === "csv" ? buildFavoritesCsv(items) : buildFavoritesExcel(items); downloadTextFile(`nukhba-favorites.${format === "csv" ? "csv" : "xls"}`, content, format === "csv" ? "text/csv" : "application/vnd.ms-excel"); setExportMessage("تم تصدير المفضلة بنجاح."); } catch { setExportMessage("تعذر تصدير المفضلة."); } finally { setExporting(false); } };
  return <div dir="rtl" className="min-h-screen bg-[#fbf8f4] text-[#182431]"><header className="border-b border-[#182431]/10 bg-white px-5 py-5"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#182431] font-bold text-[#e8a64a]">ن</span><b className="text-xl">نُخبة</b></Link><Link href="/dashboard/student" className="rounded-full bg-[#182431] px-4 py-2 text-sm font-bold text-white">لوحة الطالب</Link></div></header><main className="mx-auto max-w-5xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#ff7a00]">مساحة الطالب</p><h1 className="mt-2 text-4xl font-bold">المفضلة</h1><p className="mt-3 text-[#182431]/55">احفظ المعلمين وخطط التعلم التي تريد العودة إليها.</p></div><div className="flex items-center gap-3"><button disabled={exporting} onClick={() => exportFavorites("csv")} className="rounded-full border border-[#182431]/15 px-4 py-2 text-xs font-bold">CSV</button><button disabled={exporting} onClick={() => exportFavorites("excel")} className="rounded-full bg-[#ff7a00] px-4 py-2 text-xs font-bold text-white">{exporting ? "جارٍ التصدير…" : "Excel"}</button><Heart className="h-10 w-10 text-[#ff7a00]"/></div></div>{exportMessage && <p role="status" className="mt-4 text-sm font-semibold text-[#ff7a00]">{exportMessage}</p>}{favorites.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2">{[1,2,3,4].map(x => <div key={x} className="h-24 animate-pulse rounded-2xl bg-white"/>)}</div> : favorites.isError ? <div role="alert" className="mt-8 rounded-2xl bg-red-50 p-6 font-semibold text-red-700">تعذر تحميل المفضلة.</div> : items.length === 0 ? <div className="mt-8 rounded-[2rem] bg-white p-12 text-center"><Heart className="mx-auto h-10 w-10 text-[#ff7a00]"/><h2 className="mt-4 text-xl font-bold">لا توجد عناصر محفوظة</h2><p className="mt-2 text-sm text-[#182431]/55">ابدأ من سوق المعلمين أو لوحة الطالب لإضافة أول عنصر.</p><Link href="/teachers" className="mt-6 inline-block rounded-full bg-[#ff7a00] px-5 py-3 text-sm font-bold text-white">استكشف المعلمين</Link></div> : <div className="mt-8 grid gap-4 md:grid-cols-2">{items.map(item => <article key={item.id} className="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><div><span className="text-xs font-bold text-[#ff7a00]">{item.favoriteType === "teacher" ? "معلم" : "خطة تعلم"}</span><h2 className="mt-2 font-bold">{item.title}</h2><p className="mt-1 text-xs text-[#182431]/45">محفوظة في {new Date(item.createdAt).toLocaleDateString("ar-EG")}</p></div><button type="button" aria-label={`إزالة ${item.title}`} onClick={() => remove.mutate({ favoriteType: item.favoriteType, targetId: item.targetId })} className="rounded-full p-3 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></article>)}</div>}</main></div>;
}
