import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

const fieldLabels: Record<string, string> = { fullName: "الاسم الكامل", educationStage: "المرحلة الدراسية", grade: "الصف", learningLevel: "المستوى", learningGoals: "أهداف التعلم", strengths: "نقاط القوة", difficulties: "الصعوبات", preferredLearningFormat: "صيغة التعلم المفضلة", preferredSubjects: "المواد المفضلة", preferredAvailability: "الأوقات المناسبة" };
const profileFields = ["fullName", "educationStage", "grade", "learningLevel", "learningGoals", "strengths", "difficulties", "preferredLearningFormat", "preferredSubjects", "preferredAvailability"] as const;

export default function StudentProfile() {
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const profile = trpc.student.profile.get.useQuery();
  const update = trpc.student.profile.update.useMutation({ onSuccess: async () => { await profile.refetch(); await utils.auth.me.invalidate(); const learningProfile = await utils.student.learningProfile.get.fetch(); window.setTimeout(() => navigate(learningProfile ? "/dashboard/student" : "/onboarding"), 700); } });
  const learning = trpc.student.learningProfile.get.useQuery();
  const [form, setForm] = useState<Record<string, string>>({});
  useEffect(() => { if (profile.data) { const next: Record<string, string> = {}; for (const key of profileFields) next[key] = Array.isArray(profile.data[key]) ? (profile.data[key] as string[]).join("، ") : String(profile.data[key] ?? ""); setForm(next); } }, [profile.data]);
  const save = () => update.mutate({ ...form, preferredSubjects: form.preferredSubjects?.split("،").map(x => x.trim()).filter(Boolean), preferredAvailability: form.preferredAvailability?.split("،").map(x => x.trim()).filter(Boolean) });
  return <div dir="rtl" className="min-h-screen bg-[#f7f6f2] text-[#13233a]"><header className="border-b border-[#13233a]/10 px-5 py-5 lg:px-10"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#13233a] font-bold text-[#e8a64a]">ن</span><b className="text-xl">نُخبة</b></Link><Link href="/parent/children" className="text-sm font-bold text-[#0e7c78]">لوحة ولي الأمر</Link></div></header><main className="mx-auto max-w-5xl px-5 py-10 lg:px-10"><p className="text-sm font-bold text-[#0e7c78]">Student Foundation · Phase 2</p><h1 className="mt-2 text-4xl font-bold">ملف الطالب</h1><p className="mt-3 text-[#13233a]/55">بياناتك التعليمية محفوظة بأمان على الخادم، وليست في المتصفح.</p><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-[2rem] bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2">{profileFields.map(key => <label key={key} className={key.includes("Goals") || key.includes("strengths") || key.includes("difficulties") ? "sm:col-span-2" : ""}><span className="mb-2 block text-sm font-bold">{fieldLabels[key]}</span>{["learningGoals", "strengths", "difficulties"].includes(key) ? <textarea value={form[key] ?? ""} onChange={e => setForm(v => ({ ...v, [key]: e.target.value }))} className="min-h-24 w-full rounded-xl border border-[#13233a]/10 bg-[#f7f6f2] p-3 outline-none focus:border-[#0e7c78]" /> : <input value={form[key] ?? ""} onChange={e => setForm(v => ({ ...v, [key]: e.target.value }))} className="w-full rounded-xl border border-[#13233a]/10 bg-[#f7f6f2] p-3 outline-none focus:border-[#0e7c78]" />}</label>)}</div><button disabled={update.isPending} onClick={save} className="mt-6 rounded-full bg-[#0e7c78] px-6 py-3 font-bold text-white">{update.isPending ? "جارٍ الحفظ…" : "حفظ الملف"}</button>{update.isSuccess && <span className="mr-3 text-sm font-bold text-[#0e7c78]">تم الحفظ</span>}</section><aside className="rounded-[2rem] bg-[#13233a] p-6 text-white"><p className="text-sm text-white/55">Learning Profile</p><h2 className="mt-2 text-2xl font-bold">ملخص رحلة التعلم</h2>{learning.data ? <div className="mt-6 space-y-3 text-sm text-white/75"><p>المادة: <b className="text-white">{learning.data.subject || "—"}</b></p><p>الهدف: <b className="text-white">{learning.data.goal || "—"}</b></p><p>المستوى: <b className="text-white">{learning.data.level || "—"}</b></p><p>آخر تحديث: <b className="text-white">{new Date(learning.data.updatedAt).toLocaleDateString("ar-SA")}</b></p></div> : <p className="mt-6 text-sm leading-7 text-white/55">أكمل Smart Onboarding ليظهر ملخصك هنا.</p>}</aside></div></main></div>;
}
