import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const statusText: Record<string, string> = { pending: "طلبك قيد المراجعة", approved: "تم اعتماد ملفك", rejected: "يحتاج الطلب إلى تعديل", suspended: "تم تعليق ظهور الملف" };
export default function TeacherRegister() {
  const app = trpc.teacher.application.get.useQuery();
  const create = trpc.teacher.application.create.useMutation({ onSuccess: () => app.refetch() });
  const update = trpc.teacher.application.update.useMutation({ onSuccess: () => app.refetch() });
  const submit = trpc.teacher.application.submit.useMutation({ onSuccess: () => app.refetch() });
  const [form, setForm] = useState({ fullName: "", phone: "", country: "", city: "", profilePhotoUrl: "", qualification: "", specialization: "", bio: "", subjects: "", educationStages: "", grades: "", teachingFormat: "", availability: "", yearsOfExperience: "0", hourlyRate: "" });
  const profile = app.data;
  if (app.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f6f2]">جارٍ تحميل الطلب...</div>;
  const set = (key: string, value: string) => setForm(prev => ({ ...prev, [key]: value }));
  const payload = () => ({ fullName: form.fullName, phone: form.phone, country: form.country, city: form.city, profilePhotoUrl: form.profilePhotoUrl || null, qualification: form.qualification, specialization: form.specialization, bio: form.bio, subjects: form.subjects.split(",").map(x => x.trim()).filter(Boolean), educationStages: form.educationStages.split(",").map(x => x.trim()).filter(Boolean), grades: form.grades.split(",").map(x => x.trim()).filter(Boolean), teachingFormat: form.teachingFormat, availability: form.availability.split(",").map(x => x.trim()).filter(Boolean), yearsOfExperience: Number(form.yearsOfExperience), hourlyRate: form.hourlyRate ? Number(form.hourlyRate) : null });
  const save = (event: FormEvent) => { event.preventDefault(); const data = payload(); if (profile) update.mutate(data); else create.mutate(data); };
  const fill = () => { if (!profile) return; setForm({ fullName: profile.fullName, phone: profile.phone ?? "", country: profile.country ?? "", city: profile.city ?? "", profilePhotoUrl: profile.profilePhotoUrl ?? "", qualification: profile.qualification ?? "", specialization: profile.specialization ?? "", bio: profile.bio ?? "", subjects: profile.subjects.join(", "), educationStages: profile.educationStages.join(", "), grades: profile.grades.join(", "), teachingFormat: profile.teachingFormat ?? "", availability: profile.availability.join(", "), yearsOfExperience: String(profile.yearsOfExperience), hourlyRate: profile.hourlyRate ? String(profile.hourlyRate) : "" }); };
  useEffect(() => { if (profile && !form.fullName) fill(); }, [profile]);
  return <main dir="rtl" className="min-h-screen bg-[#f7f6f2] px-5 py-10 text-[#13233a] lg:px-16"><div className="mx-auto max-w-4xl"><Link href="/" className="text-sm font-bold text-[#0e7c78]">العودة للرئيسية</Link><div className="mt-6 rounded-[2rem] bg-white p-7 shadow-sm"><p className="text-sm font-bold text-[#0e7c78]">تسجيل المعلمين</p><h1 className="mt-2 text-3xl font-bold">ملفك المهني في نُخبة</h1>{profile && <div className="mt-5 rounded-2xl bg-[#e9f5ef] p-4"><b>{statusText[profile.verificationStatus]}</b>{profile.rejectionReason && <p className="mt-2 text-sm">سبب الرفض: {profile.rejectionReason}</p>}</div>}<form onSubmit={save} className="mt-7 grid gap-4 sm:grid-cols-2">{[["fullName","الاسم الكامل"],["phone","رقم الهاتف"],["country","الدولة"],["city","المدينة"],["profilePhotoUrl","رابط الصورة الشخصية"],["qualification","المؤهل"],["specialization","التخصص"],["yearsOfExperience","سنوات الخبرة"],["subjects","المواد (افصل بفاصلة)"],["educationStages","المراحل التعليمية (افصل بفاصلة)"],["grades","الصفوف (افصل بفاصلة)"],["teachingFormat","صيغة التدريس"],["availability","الأوقات المتاحة (افصل بفاصلة)"],["hourlyRate","السعر بالساعة"]].map(([key,label]) => <label key={key} className="text-sm font-bold">{label}<input required={key === "fullName"} type={key === "yearsOfExperience" || key === "hourlyRate" ? "number" : "text"} value={form[key as keyof typeof form]} onChange={e => set(key, e.target.value)} className="mt-2 w-full rounded-xl border border-[#13233a]/10 bg-[#f7f6f2] p-3 font-normal outline-none" /></label>)}<label className="sm:col-span-2 text-sm font-bold">نبذة مهنية<textarea value={form.bio} onChange={e => set("bio", e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-[#13233a]/10 bg-[#f7f6f2] p-3 font-normal outline-none" /></label><button disabled={create.isPending || update.isPending} className="rounded-full bg-[#13233a] px-5 py-3 font-bold text-white sm:col-span-2">حفظ الملف</button></form>{profile && profile.verificationStatus !== "suspended" && profile.verificationStatus !== "approved" && <button onClick={() => submit.mutate()} disabled={submit.isPending} className="mt-4 w-full rounded-full bg-[#0e7c78] px-5 py-3 font-bold text-white">إرسال الطلب للمراجعة</button>}</div></div></main>;
}
